---
- name: Provision AWS VPC network
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: MyVPC
        cidr_block: 10.0.0.0/16
        region: us-east-1
        state: present
      register: vpc_net

    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc_net.vpc.id }}"
        region: us-east-1
        state: present
      register: igw

    - name: Create Public Subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_net.vpc.id }}"
        cidr: 10.0.0.0/24
        region: us-east-1
        state: present
        map_public: yes
      register: public_subnet

    - name: Create Private Subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_net.vpc.id }}"
        cidr: 10.0.1.0/24
        region: us-east-1
        state: present
      register: private_subnet

    - name: Create Public Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc_net.vpc.id }}"
        region: us-east-1
        state: present
        subnets:
          - "{{ public_subnet.subnet.id }}"
      register: public_route_table

    - name: Create API Security Group
      ec2_group:
        name: API_SG
        description: Security group for API servers
        vpc_id: "{{ vpc_net.vpc.id }}"
        region: us-east-1
        state: present

    - name: Create Security Group for Database Server
      ec2_group:
        name: DB_SG
        description: Security Group for Database Server
        vpc_id: "{{ vpc_net.vpc.id }}"
        region: us-east-1
        state: present
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            group_name: API_SG

