---
- name: Provision AWS VPC network
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: MyVPC
        cidr_block: 10.0.0.0/16
        region: us-east-1
        state: present
      register: vpc

    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc_id }}"
        region: us-east-1
        state: present
      register: igw

    - name: Create Public Subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc_id }}"
        cidr: 10.0.0.0/24
        region: us-east-1
        state: present
        map_public: yes
      register: public_subnet

    - name: Create Private Subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc_id }}"
        cidr: 10.0.1.0/24
        region: us-east-1
        state: present
      register: private_subnet

    - name: Create Public Route Table
      ec2_vpc_routetable:
        vpc_id: "{{ vpc.vpc_id }}"
        region: us-east-1
        state: present
        subnets:
          - "{{ public_subnet.subnet_id }}"
      register: public_route_table

    - name: Associate Public Subnet with Public Route Table
      ec2_vpc_routetable_association:
        subnet_id: "{{ public_subnet.subnet_id }}"
        route_table_id: "{{ public_route_table.route_table_id }}"
        region: us-east-1
        state: present

    - name: Create API Security Group
      ec2_group:
        name: API-SG
        description: Security group for API servers
        vpc_id: "{{ vpc.vpc_id }}"
        region: us-east-1
        state: present
      register: api_security_group

    - name: Create Database Security Group
      ec2_group:
        name: Database-SG
        description: Security group for database servers
        vpc_id: "{{ vpc.vpc_id }}"
        region: us-east-1
        state: present
        rules:
          - proto: tcp
            ports:
              - 3306
            from_port: 3306
            to_port: 3306
            group_name: "{{ api_security_group.group_name }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: db_security_group

